name: PrivateIPs Check

on:
  pull_request:
    branches:
      - master
    paths:
      - "net/*.sls"
  workflow_dispatch:

env:
  GH_PR_BASE_REF: ${{ github.event.pull_request.base.sha }}
  GH_PR_HEAD_REF: ${{ github.event.pull_request.head.sha }}

jobs:
  check-for-privateIPs:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      - name: Install needed packages
        run: |
          apt update && apt install -y git python3  python3-yaml      

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: set files changed env variable
        if: env.GH_PR_HEAD_REF
        run: |
          pwd
          whoami
          ls -l /__w/privIP_test
          /usr/bin/git config --global --add safe.directory .
          git log -5 --oneline | cat
          echo "FILES_CHANGED=$(git diff --name-only ${GH_PR_BASE_REF} ${GH_PR_HEAD_REF} | grep -w net | xargs)" >> $GITHUB_ENV
        shell: bash

      - name:  checkout master/pr version of files and create diff containing ip adds and deletions for each changed file
        if: env.GH_PR_HEAD_REF
        run: |
          for file in $FILES_CHANGED; do
            git show ${GH_PR_BASE_REF}:$file > $file.master || touch $file.master    #### ensures an empty *.master file is created for any new file in pr
            git show ${GH_PR_HEAD_REF}:$file > $file.pr || touch $file.pr        #### ensures an empty *.pr file is created for any deleted file in pr
            git diff ${GH_PR_BASE_REF} ${GH_PR_HEAD_REF} --unified=0 -- $file > $file.gitdiff
          done

      - name: Run check script
        run: |
          ${GITHUB_WORKSPACE}/.github/privips.py $FILES_CHANGED
        shell: bash
